### ISSUE TITLE
Bug in Panel.get_body()

### ISSUE THREAD

**Issue by Riebart** [Riebart/vivint.py#2]
```>>> p.get_body()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Documents/vivint.py/vivint.py", line 104, in get_body
    return self._body
AttributeError: 'PanelRoot' object has no attribute '_body'```

**Comment by Riebart** [comment]
Closing this because there's no context, and no way to reproduce...
